// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDApzeei4UEDurU-hnFS8eNHr_jNUdXDco',
    appId: '1:222454861457:web:749707568129059ac2b930',
    messagingSenderId: '222454861457',
    projectId: 'chat-app-8a607',
    authDomain: 'chat-app-8a607.firebaseapp.com',
    storageBucket: 'chat-app-8a607.appspot.com',
    measurementId: 'G-K1B2M0HMHJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrGHZFaJ5Y8-BnHslmctFhwfAAdwxYAbY',
    appId: '1:222454861457:android:538ecc4947378df5c2b930',
    messagingSenderId: '222454861457',
    projectId: 'chat-app-8a607',
    storageBucket: 'chat-app-8a607.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTH3nMuwjNtALDcA2WwUL1smd36UpHAkA',
    appId: '1:222454861457:ios:fd45a00959b7cc9ac2b930',
    messagingSenderId: '222454861457',
    projectId: 'chat-app-8a607',
    storageBucket: 'chat-app-8a607.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTH3nMuwjNtALDcA2WwUL1smd36UpHAkA',
    appId: '1:222454861457:ios:fd45a00959b7cc9ac2b930',
    messagingSenderId: '222454861457',
    projectId: 'chat-app-8a607',
    storageBucket: 'chat-app-8a607.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDApzeei4UEDurU-hnFS8eNHr_jNUdXDco',
    appId: '1:222454861457:web:4535069465f9a2f9c2b930',
    messagingSenderId: '222454861457',
    projectId: 'chat-app-8a607',
    authDomain: 'chat-app-8a607.firebaseapp.com',
    storageBucket: 'chat-app-8a607.appspot.com',
    measurementId: 'G-JPX7FCL5PJ',
  );

}